version: 3

tasks:
  build:
    deps:
      - build_lz4_frames
      - build_lz4_blocks
    method: none
    silent: true
  
  build_lz4_frames:
    cmds:
      - odin build lz4-frames -out:bin/lz4-frames -o:speed
    sources:
      - lz4/**/*.odin
      - lz4-frames/**/*.odin
    generates:
      - bin/lz4-frames
    silent: true

  build_lz4_blocks:
    cmds:
      - odin build lz4-blocks -out:bin/lz4-blocks -o:speed
    sources:
      - lz4/**/*.odin
      - lz4-blocks/**/*.odin
    generates:
      - bin/lz4-blocks
    silent: true

  test:
    deps:
      - test_lz4
    method: none
    silent: true
    aliases:
      - t

  test_lz4:
    cmds:
      - odin test lz4 -out:bin/lz4-test -o:speed
    sources:
      - lz4/**/*.odin
    generates:
      - bin/lz4-test
    method: none
    silent: true

  debug_test_lz4:
    cmds:
      - gdb bin/lz4-test
    method: none
    silent: true
    aliases:
      - dt

  decompression_ui:
    deps:
      - build_decompression_ui
    cmds:
      - bin/decompression-ui
    method: none
    silent: true

  build_decompression_ui:
    cmds:
      - odin build decompression-ui -out:bin/decompression-ui -o:none -debug -collection:dependencies=dependencies
    sources:
      - decompression-ui/**/*.odin
      - dependencies/imgui/**/*.odin
    generates:
      - bin/decompression-ui
    silent: true

  debug_decompression_ui:
    cmds:
      - gdb bin/decompression-ui
    method: none
    silent: true

  build_ui_lib:
    cmds:
      - odin build decompression-ui/ui -out:bin/ui-new -o:none -debug -collection:dependencies=dependencies -build-mode:shared
      - mv bin/ui-new.so bin/ui.so
    sources:
      - decompression-ui/ui/**/*.odin
      - lz4/**/*.odin
      - dependencies/imgui/**/*.odin
    generates:
      - bin/ui.so
    silent: true

interval: 100ms

