version: 3

tasks:
  build:
    deps:
      - build_lz4_frames
      - build_lz4_blocks
    method: none
    silent: true
  
  build_lz4_frames:
    cmds:
      - odin build lz4-frames -out:bin/lz4-frames -o:speed
    sources:
      - lz4/**/*.odin
      - lz4-frames/**/*.odin
    generates:
      - bin/lz4-frames
    silent: true

  build_lz4_blocks:
    cmds:
      - odin build lz4-blocks -out:bin/lz4-blocks -o:speed
    sources:
      - lz4/**/*.odin
      - lz4-blocks/**/*.odin
    generates:
      - bin/lz4-blocks
    silent: true

  test:
    deps:
      - test_lz4
    method: none
    silent: true
    aliases:
      - t

  test_lz4:
    cmds:
      - odin test lz4 -out:bin/lz4-test -o:speed
    sources:
      - lz4/**/*.odin
    generates:
      - bin/lz4-test
    method: none
    silent: true

  debug_test_lz4:
    cmds:
      - gdb bin/lz4-test
    method: none
    silent: true
    aliases:
      - dt

interval: 100ms

